services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-whatsapp-integration
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - app-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-service
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: http app:3000 --log=stdout
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
