services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-whatsapp-integration
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
